# Generated by Django 2.2.3 on 2019-10-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='keywords',
        ),
    ]
