# Generated by Django 2.2.3 on 2019-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslisting', '0003_auto_20191012_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outlet',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
